// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/tools/list-courses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/data/courses.ts
var SITE_URL = "https://jume-grow-thrive.lovable.app";
var courses = [
  {
    "title": "Animal Humane Education",
    "slug": "animal-humane-education",
    "prospectusPath": "/prospectus/ANIMAL_HUMANE_EDUCATION.pdf",
    "summary": "Importance of livestock in food security, animal nutrition & feeding, breeding & genetics, livestock management, animal health, dairy/poultry/beef/pig production, plus agribusiness & technology. Practical sessions cover handling, vaccination, feed formulation and farm business management."
  },
  {
    "title": "Agro-ecology & Agro-biodiversity",
    "slug": "agro-ecology-agro-biodiversity",
    "prospectusPath": "/prospectus/AGRO.pdf",
    "summary": "Ecological principles, soil management, natural pest control, agroforestry & apiculture, food sovereignty and family nutrition, plus market and value-addition. Builds an integrated, holistic understanding of food systems for long-term agro-ecological transformation."
  },
  {
    "title": "Agricultural Engineering",
    "slug": "agricultural-engineering",
    "prospectusPath": "/prospectus/AGRICULTURAL_ENGINEERING.pdf",
    "summary": "Applied engineering for agriculture \u2014 farm machinery, irrigation systems, post-harvest technology, soil & water engineering, and precision agriculture. Combines workshop practice with farm-based projects."
  },
  {
    "title": "Building Technology",
    "slug": "building-technology",
    "prospectusPath": "/prospectus/BUILDING_TECHNOLOGY.pdf",
    "summary": "Masonry, technical drawing, structural mechanics, site management and sustainable building practice. Certificate and Diploma pathways with industrial attachment."
  },
  {
    "title": "Carpentry & Joinery",
    "slug": "carpentry-joinery",
    "prospectusPath": "/prospectus/CARPENTRY_AND_JOINERY.pdf",
    "summary": "Hands-on training in woodwork, joinery, furniture making and finishing. Equips graduates with employable skills and the foundation to start their own workshops."
  },
  {
    "title": "Community Development",
    "slug": "community-development",
    "prospectusPath": "/prospectus/COMMUNITY_DEVELOPMENT.pdf",
    "summary": "Skills to plan, implement and evaluate community initiatives \u2014 needs assessment, project management, resource mobilisation and leadership. Prepares practitioners for roles in NGOs, government agencies and community-based organisations."
  },
  {
    "title": "Computer & Information Technology",
    "slug": "computer-information-technology",
    "prospectusPath": "/prospectus/COMPUTER_AND_INFORMATION_TECHNOLOGY.pdf",
    "summary": "Computer fundamentals, networking, cyber security, ICT technician skills and AI basics \u2014 equipping students for the modern digital workplace."
  },
  {
    "title": "Cooking Skills",
    "slug": "cooking-skills",
    "prospectusPath": "/prospectus/COOKING_SKILLS.pdf",
    "summary": "Culinary arts, food preparation, nutrition, kitchen management, and food safety & hygiene. Practical kitchen training for hotels, restaurants, and self-employment."
  },
  {
    "title": "Baking Technology",
    "slug": "baking-technology",
    "prospectusPath": "/prospectus/BAKING_TECHNOLOGY.pdf",
    "summary": "Bakery and pastry production, dough science, bread, cakes and confectionery, plus bakery business management. Hands-on training preparing graduates for community bakeries and self-employment."
  },
  {
    "title": "Accommodation Operations",
    "slug": "accommodation-operations",
    "prospectusPath": "/prospectus/ACCOMMODATION_OPERATIONS.pdf",
    "summary": "Front office, housekeeping, guest services, hospitality standards and accommodation management \u2014 pathways to careers in hotels, lodges and the wider tourism sector."
  },
  {
    "title": "Soap Making (Short Course)",
    "slug": "soap-making-short-course",
    "prospectusPath": "/prospectus/OTEPIC_Agricultural_Modular_Courses_Prospectus.pdf",
    "summary": "Saponification science, safe lye handling, cold-press and hot-press techniques, liquid soap, shower gel, washing soap and gardener soap. A practical income-generating skill for women's groups, youth and small enterprises."
  },
  {
    "title": "Tailoring & Garment Making",
    "slug": "tailoring-garment-making",
    "prospectusPath": "/prospectus/TAILORING_COURSE.pdf",
    "summary": "Modular vocational training (Grades III, II and I) \u2014 from basic stitching to advanced garment construction, pattern cutting, costing and small-business management."
  },
  {
    "title": "Permaculture Course",
    "slug": "permaculture-course",
    "prospectusPath": "/prospectus/PERMACULTURE_COURSE.pdf",
    "summary": "A standardised 72-hour curriculum focused on ecological design, sustainability, and regenerative practice. Delivered over two weeks, weekend series, or online."
  },
  {
    "title": "Grow Bio-Intensive Course",
    "slug": "grow-bio-intensive-course",
    "prospectusPath": "/prospectus/GROW_BIO_INTENSIVE_COURSE.pdf",
    "summary": "Deep-bed soil preparation, intensive planting, composting and calorie-and-compost crop ratios \u2014 produce more food on less land while building soil."
  },
  {
    "title": "Horticulture",
    "slug": "horticulture",
    "prospectusPath": "/prospectus/HORTICULTURE.pdf",
    "summary": "Vegetable, fruit and ornamental crop production, nursery management, greenhouse operations, IPM and post-harvest handling."
  },
  {
    "title": "Cosmetology",
    "slug": "cosmetology",
    "prospectusPath": "/prospectus/COSMETOLOGY.pdf",
    "summary": "Beauty therapy, hairdressing, skincare and salon management \u2014 practical training for self-employment and salon careers."
  },
  {
    "title": "Electrical Installation",
    "slug": "electrical-installation",
    "prospectusPath": "/prospectus/ELECTRICAL_INSTALLATION.pdf",
    "summary": "Domestic and industrial electrical wiring, circuits, safety standards and installation practice \u2014 pathway to certified electrician work."
  },
  {
    "title": "Environmental Science",
    "slug": "environmental-science",
    "prospectusPath": "/prospectus/ENVIRONMENTAL_SCIENCE.pdf",
    "summary": "Ecology, climate change, conservation, environmental impact assessment and natural resource management for sustainability practitioners."
  },
  {
    "title": "Fashion Designer",
    "slug": "fashion-designer",
    "prospectusPath": "/prospectus/FASHION_DESIGNER.pdf",
    "summary": "Design, pattern making, garment construction, textiles and fashion business \u2014 build a career or launch your own clothing line."
  },
  {
    "title": "Food & Beverage Operations",
    "slug": "food-beverage-operations",
    "prospectusPath": "/prospectus/FOOD_AND_BEVERAGE_OPERATIONS.pdf",
    "summary": "Restaurant service, bar operations, menu knowledge and customer service standards for the hospitality industry."
  },
  {
    "title": "Food Processing Technology",
    "slug": "food-processing-technology",
    "prospectusPath": "/prospectus/FOOD_PROCESSING_TECHNOLOGY.pdf",
    "summary": "Food preservation, value addition, packaging, food safety and small-scale processing enterprise \u2014 turning harvests into shelf-stable products."
  },
  {
    "title": "Sustainable Agriculture Course",
    "slug": "sustainable-agriculture-course",
    "prospectusPath": "/prospectus/SUSTAINABLE_AGRICULTURE_COURSE.pdf",
    "summary": "Soil health, organic production, water conservation, integrated pest management and farm-based enterprise \u2014 equipping farmers with practical, climate-smart and regenerative agriculture skills for long-term food security."
  },
  {
    "title": "Welding & Fabrication",
    "slug": "welding-fabrication",
    "prospectusPath": "/prospectus/WELDING_AND_FABRICATION.pdf",
    "summary": "Arc and gas welding, sheet-metal work, structural fabrication, workshop safety and project costing \u2014 practical skills for employment in construction, agriculture and self-run metal workshops."
  },
  {
    "title": "Plumbing",
    "slug": "plumbing",
    "prospectusPath": "/prospectus/PLUMBING.pdf",
    "summary": "Domestic and commercial plumbing systems, pipefitting, drainage, water supply, sanitation installation and maintenance \u2014 preparing graduates for certified plumbing work and small-business setups."
  }
];

// src/lib/mcp/tools/list-courses.ts
var list_courses_default = defineTool({
  name: "list_courses",
  title: "List courses",
  description: "List the training courses offered by JUME College - OTEPIC Kenya, with a summary and prospectus PDF link for each.",
  inputSchema: {
    search: z.string().trim().min(1).optional().describe("Optional keyword to filter courses by title or summary.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ search }) => {
    const q = search?.toLowerCase();
    const matches = q ? courses.filter((c) => `${c.title} ${c.summary}`.toLowerCase().includes(q)) : courses;
    const rows = matches.map((c) => ({
      title: c.title,
      slug: c.slug,
      summary: c.summary,
      prospectusUrl: `${SITE_URL}${c.prospectusPath}`
    }));
    const text = rows.length ? rows.map((r) => `${r.title}
${r.summary}
Prospectus: ${r.prospectusUrl}`).join("\n\n") : `No courses matched "${search}".`;
    return { content: [{ type: "text", text }], structuredContent: { count: rows.length, courses: rows } };
  }
});

// src/lib/mcp/tools/get-course.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_course_default = defineTool2({
  name: "get_course",
  title: "Get course details",
  description: "Get full details and the prospectus PDF link for one course, by its title or slug.",
  inputSchema: {
    course: z2.string().trim().min(1).describe("Course title or slug, e.g. 'Permaculture Course' or 'plumbing'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ course }) => {
    const q = course.toLowerCase();
    const match = courses.find((c) => c.slug === q || c.title.toLowerCase() === q) ?? courses.find((c) => c.title.toLowerCase().includes(q) || c.slug.includes(q.replace(/\s+/g, "-")));
    if (!match) {
      throw new ToolError(`No course found matching "${course}". Use list_courses to see all courses.`);
    }
    const row = {
      title: match.title,
      slug: match.slug,
      summary: match.summary,
      prospectusUrl: `${SITE_URL}${match.prospectusPath}`,
      pageUrl: `${SITE_URL}/projects`
    };
    return {
      content: [{ type: "text", text: `${row.title}

${row.summary}

Prospectus: ${row.prospectusUrl}
Page: ${row.pageUrl}` }],
      structuredContent: { course: row }
    };
  }
});

// src/lib/mcp/tools/get-college-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.1";
var info = {
  name: "JUME College - OTEPIC Kenya",
  description: "A community based not-for-profit organization in Trans Nzoia County, Kenya, offering vocational and agricultural training, permaculture and community development programs.",
  director: "Philip Munyasia",
  location: "Upendo Farm, Trans Nzoia County, Kenya",
  phone: "+254 725 429 179",
  email: "otepic07@yahoo.com",
  website: SITE_URL,
  pages: {
    about: `${SITE_URL}/about`,
    trainingsAndProjects: `${SITE_URL}/projects`,
    gallery: `${SITE_URL}/gallery`,
    impact: `${SITE_URL}/impact`,
    reportsAndNewsletters: `${SITE_URL}/newsletters`,
    tabasamuChildrensHome: `${SITE_URL}/tabasamu`,
    donate: `${SITE_URL}/donate`,
    contact: `${SITE_URL}/contact`
  }
};
var get_college_info_default = defineTool3({
  name: "get_college_info",
  title: "Get college info",
  description: "Get contact details, location, director and key page links for JUME College - OTEPIC Kenya.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: `${info.name}
${info.description}

Director: ${info.director}
Location: ${info.location}
Phone: ${info.phone}
Email: ${info.email}
Website: ${info.website}`
      }
    ],
    structuredContent: { info }
  })
});

// src/lib/mcp/tools/get-impact-stats.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@3.0.1";
var stats = [
  { label: "Farmers Reached", value: "30,000+" },
  { label: "Adoption Rate", value: "52%" },
  { label: "Synthetic Input Reduction", value: "60%" },
  { label: "Income Increase", value: "30%" },
  { label: "People Provided with Clean Drinking Water", value: "3,000+" }
];
var supportGoes = [
  "Installing water tanks for the demonstration farms",
  "Planting trees for fruits and shades",
  "Training farmers on solar dryers",
  "Setting up mushroom production units for production and training",
  "Buying farm tools and equipment",
  "Buying seeds",
  "Supporting Tabasamu Orphanage",
  "Paying salaries",
  "Making training materials",
  "Covering administrative costs",
  "Supporting life coping skills training"
];
var get_impact_stats_default = defineTool4({
  name: "get_impact_stats",
  title: "Get impact stats",
  description: "Get the college's headline impact numbers and where donations are used.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: `Impact
${stats.map((s) => `- ${s.label}: ${s.value}`).join("\n")}

Where your support goes
${supportGoes.map((s) => `- ${s}`).join("\n")}

Details: ${SITE_URL}/impact`
      }
    ],
    structuredContent: { stats, supportGoes, impactPageUrl: `${SITE_URL}/impact` }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "jume-college-portal",
  title: "Jume College Portal",
  version: "0.1.0",
  instructions: "Public tools for JUME College - OTEPIC Kenya. Use `list_courses` and `get_course` for training courses and their prospectus PDFs, `get_college_info` for contact details and page links, and `get_impact_stats` for impact numbers and how donations are used.",
  tools: [list_courses_default, get_course_default, get_college_info_default, get_impact_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
